# Generated by Django 5.2.16 on 2026-07-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_appointment_medicine_appointment_quantity_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinerecord',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medicinerecord',
            name='prescription',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the medicine', null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='quantity_requested',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Pain Reliever, Antibiotic', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(default='pcs', help_text='e.g. pcs, bottles, boxes', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.student'),
        ),
    ]
