# Generated by Django 5.2.16 on 2026-07-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_medicinerecord_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerecord',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinerecord',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinerecord',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='medicinerecord',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
