# Generated by Django 5.2.16 on 2026-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_nurse_user_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='schedule',
            field=models.CharField(blank=True, help_text='hal. Mon-Fri, 8AM-5PM (Time of Duty)', max_length=150),
        ),
    ]
