# Generated by Django 5.2.16 on 2026-08-04 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_nurse_age_alter_nurse_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('student', 'Student'), ('medicine', 'Medicine'), ('nurse', 'Nurse'), ('dispense', 'Dispense'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(help_text="hal. 'New student registered'", max_length=200)),
                ('description', models.CharField(blank=True, help_text="hal. 'Juan Dela Cruz added'", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
