# Generated by Django 5.2.16 on 2026-07-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, help_text='hal. Pain Reliever, Antibiotic', max_length=100)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', help_text='hal. pcs, bottles, boxes', max_length=30)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
