# Generated by Django 5.2.16 on 2026-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_profile_photo_delete_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='nurse_photos/')),
                ('position', models.CharField(blank=True, help_text='hal. School Nurse, Clinic Head', max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('schedule', models.CharField(blank=True, help_text='hal. Mon-Fri, 8AM-5PM', max_length=150)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
