# Generated by Django 5.2.16 on 2026-07-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to='clinic.medicine'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='quantity_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
