# Generated by Django 5.2.16 on 2026-07-28 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_remove_medicinerecord_dosage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinerecord',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='medicinerecord',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='medicinerecord',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, help_text='hal. Pain Reliever, Antibiotic', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(default='pcs', help_text='hal. pcs, bottles, boxes', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='clinic.student'),
        ),
    ]
