# Generated by Django 5.2.16 on 2026-07-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_medicinerecord_dosage_medicinerecord_expiration_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineRequest',
        ),
    ]
