# Generated by Django 5.2.16 on 2026-08-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='title',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='action_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='description',
            new_name='details',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
