# Generated by Django 5.2.16 on 2026-08-05 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_rename_title_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True, help_text='Kumpletong detalye ng aktibidad', null=True),
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicine')),
            ],
        ),
    ]
