# Generated by Django 5.2.16 on 2026-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_activitylog_description_dispenserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('student', 'Student'), ('medicine', 'Medicine'), ('nurse', 'Nurse'), ('details', 'Description'), ('dispense', 'Dispense'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
