# Generated by Django 5.2.16 on 2026-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_alter_activitylog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('nurse', 'Nurse')], default='student', max_length=10),
        ),
    ]
