# Generated by Django 5.2.16 on 2026-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_recycle_bin_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('student', 'Student'), ('medicine', 'Medicine'), ('nurse', 'Assistant'), ('details', 'Description'), ('dispense', 'Dispense'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('nurse', 'Assistant')], default='student', max_length=10),
        ),
    ]
