# Generated by Django 5.2.16 on 2026-09-11 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_alter_activitylog_category_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='module',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='module',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='system', max_length=30)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
